### PR TITLE
Adds addins DCF file for rstudio addins

### PR DESCRIPTION
**Pull request by rsangole**

### CODE REVIEW

**Comment by rsangole** [comment]
@KentonWhite I haven't used travis-ci before. Could you help me decode what the error is?

**Comment by Hugovdberg** [comment]
It seems there is something else going on, not with your commit. You can view the error by clicking on the Details link in the checks for the pull request. Travis-CI isn't able to load `tuneR`, which is in the list of suggested packages. You could retry the check by temporarily closing the PR and then reopening it. This forces Travis-CI to restart the check all over.

**Comment by KentonWhite** [comment]
I'm traveling out of the country this week.  I'll see if I can help in a day or two.

**Comment by rsangole** [comment]
Thanks @Hugovdberg . I'll wait for @KentonWhite .

**Comment by KentonWhite** [comment]
There were a couple of issues with how Travis was working.  I've fixed those now.  Can you merge from master and resubmit the PR please  — the Travis errors should be fixed.

**Comment by rsangole** [comment]
@KentonWhite, I did the merge using the Github button, and it's merged & closed the issue. Yet, I think I see a Travis fail, yes? Perhaps I haven't done it correctly. Could you review?

projecttemplate__--all_-_gitk

**Comment by KentonWhite** [comment]
Everything looks ok.

**Pull request merged**
