### PR TITLE
Fixes rstudio project file creation

### PR DESCRIPTION
**Pull request by rsangole**
#### Types of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other (documentation etc)

#### Pull request checklist

 - [x] Add functionality
 - [ ] Add tests
 - [ ] Update documentation in `man`
 - [ ] Update website documentation

***

#### Proposed changes

- Rstudio file function had a missing '\n' creating a non-functioning project file.
- This commit adds a new line character

### CODE REVIEW

**Comment by Hugovdberg** [comment]
You could perhaps, instead of writing a file from a function, create a new file in `inst/defaults/` and call `file.copy(system.file([...]))`. Perhaps call it `inst/defaults/rstudio/rstudio.rproj`, and copy it using 

```R
file.copy(system.file(file.path('defaults', 'rstudio', 'rstudio.rproj')), 
          file.path(project.dir, paste0(project.name, '.rproj'))
```

The `system.file` function prepends the path to the `inst` directory of a given package. This allows you to retrieve a file from the installation directory. The `file.copy` function can rename the file in one go to the project name.

**Comment by rsangole** [comment]
@Hugovdberg lovely. That's the sort of path I wanted to adopt initially but wasn't sure if we have a 'space' where we're OK saving files like these.

Will send another commit later today.

**Comment by KentonWhite** [comment]
@rsangole did I miss the new commit?  is this ready to be reviewed and merged?

**Comment by KentonWhite** [comment]
Temporarily closing — seems to be stale.

@rsangole if this is ready to commit please reopen the PR.

**Pull request closed without merging**
